spring.application.name=cadastro-usuario
#Define o nome da aplicação Spring Boot.
spring.h2.console.enabled=true
#Habilita o console do banco H2
spring.h2.console.path=/h2-console
#Define o caminho para acessar o console H2
spring.datasource.url=jdbc:h2:mem:testdb
#Configura o banco H2 em memória / Nome para o H2
spring.datasource.driverClassName=org.h2.Driver
#Define o driver JDBC do H2
spring.datasource.username=sa
#Define o usuário do banco
spring.datasource.password=


#Se for mudar o bando de dados, é necessário alterar as configurações acima e adicionar a dependência do banco no arquivo pom.xml.
